# Generated by Django 4.2.5 on 2023-09-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('relation', models.CharField(max_length=200)),
                ('unique_number', models.CharField(max_length=100)),
            ],
        ),
    ]
