version: "3.8"

volumes:
  db:

services:
  postgres:
    image: postgres:16.0-alpine
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
